from enum import Enum


class DocumentStatus(str, Enum):
    UPLOADED = "UPLOADED"
    TG_PENDING = "TG_PENDING"

    TG_APPROVED = "TG_APPROVED"
    TG_REJECTED = "TG_REJECTED"

    SLACK_PENDING = "SLACK_PENDING"
    SLACK_APPROVED = "SLACK_APPROVED"
    SLACK_REJECTED = "SLACK_REJECTED"

    APPROVED = "APPROVED"
    REJECTED = "REJECTED"

    OCR_FAILED = "OCR_FAILED"
    DEPOSIT_FAILED = "DEPOSIT_FAILED"


class DepositStatus(str, Enum):
    DEPOSIT_PENDING = "DEPOSIT_PENDING"
    DEPOSIT_SUCCESS = "DEPOSIT_SUCCESS"
    DEPOSIT_FAILED = "DEPOSIT_FAILED"