from enum import Enum

class DocumentStatus(str, Enum):
    PENDING = "PENDING"
    TG_APPROVED = "TG_APPROVED"
    TG_REJECTED = "TG_REJECTED"
    SLACK_PENDING = "SLACK_PENDING"
    APPROVED = "APPROVED"
    SLACK_REJECTED = "SLACK_REJECTED"

class DepositStatus(str, Enum):
    DEPOSIT_PENDING = "DEPOSIT_PENDING"
    DEPOSIT_SUCCESS = "DEPOSIT_SUCCESS"
    DEPOSIT_FAILED = "DEPOSIT_FAILED"
